create table member
(
    created_at timestamp(6),
    member_id  bigint generated by default as identity,
    updated_at timestamp(6),
    nickname   varchar(255) not null unique,
    primary key (member_id)
);

create table point
(
    has_post    boolean      not null,
    is_deleted  boolean      not null,
    latitude    float(53)    not null,
    longitude   float(53)    not null,
    created_at  timestamp(6),
    point_id    bigint generated by default as identity,
    recorded_at timestamp(6) not null,
    trip_id     bigint       not null,
    updated_at  timestamp(6),
    primary key (point_id)
);

create table post
(
    created_at timestamp(6),
    member_id  bigint,
    point_id   bigint unique,
    post_id    bigint generated by default as identity,
    trip_id    bigint       not null,
    updated_at timestamp(6),
    address    varchar(255) not null,
    title      varchar(255) not null,
    writing    clob,
    primary key (post_id)
);

create table trip
(
    status     tinyint not null check (status between 0 and 1),
    created_at timestamp(6),
    member_id  bigint,
    trip_id    bigint generated by default as identity,
    updated_at timestamp(6),
    name       varchar(255),
    primary key (trip_id)
);

alter table if exists point
    add constraint FK5mdl5098jhes8wqx2j10je129
    foreign key (trip_id)
    references trip;

alter table if exists post
    add constraint FK83s99f4kx8oiqm3ro0sasmpww
    foreign key (member_id)
    references member;

alter table if exists post
    add constraint FKsv08ixd24t9ni2it37ckt52u5
    foreign key (point_id)
    references point;

alter table if exists trip
    add constraint FKgf7dax815o3frjeepa0g6u6hy
    foreign key (member_id)
    references member;
